version: '3.8'

services:
  web:
    build: ./web
    volumes:
      - ../web:/var/www/html/
    ports:
    - ${WEB_PORT}:8080
    working_dir: /var/www/html

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

  pgsql:
    image: postgres:11.12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_USER: ${PGSQL_USER}
    ports:
      - ${PGSQL_PORT}:5432

  composer:
    image: composer:2.0
    volumes:
    - ../web:/var/www/html/
    working_dir: /var/www/html/
    command: composer install --ignore-platform-reqs